'use client'

import React from 'react'
import { useField, useFormFields, TextInput } from '@payloadcms/ui'

interface TitleFieldProps {
  path: string
  required?: boolean
}

const TitleField: React.FC<TitleFieldProps> = ({ path, required }) => {
  const { value, setValue } = useField<string>({ path })

  // Get stepType and questionType from the form
  const stepTypeField = useFormFields(([fields]) => fields?.stepType)
  const questionTypeField = useFormFields(([fields]) => fields?.questionType)

  const stepType = stepTypeField?.value
  const questionType = questionTypeField?.value

  // Check if this is an auto-generated question type (should be read-only)
  const isAutoGeneratedQuestion =
    stepType === 'question' &&
    (questionType === 'rating' || questionType === 'this_or_that' || questionType === 'this_or_that_with_alternates' || questionType === 'ranking')

  return (
    <div className="field-type text">
      <label className="field-label">
        Title
        {required && <span className="required">*</span>}
      </label>
      {isAutoGeneratedQuestion && (
        <p className="field-description" style={{ marginBottom: '0.5rem', color: '#666' }}>
          Auto-generated from the selected item(s)
        </p>
      )}
      <TextInput
        path={path}
        value={value}
        onChange={setValue}
        readOnly={isAutoGeneratedQuestion}
        placeholder={isAutoGeneratedQuestion ? 'Will be auto-generated...' : 'Enter title'}
      />
    </div>
  )
}

export default TitleField
